### ISSUE TITLE
OpenStudio v2.9.0 Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#3683]
- [x] Release standards gem (if needed), Andrew
- [x] Release workflow gem (if needed), Ry
- [x] Release extension gem (if needed), (TBD)
- [x] Release measure tester gem (if needed), Nick
- [x] Double check gem files for correct versions of standards and workflow gems (use released versions only), Tim
- [x] Build openstudio-gems tar.gz for develop and develop3 and upload to s3., Tim

**If New E+ release**:
* [x] Bump E+ package in CMakeLists.txt
* [x] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [x] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./openstudiocore/src/energyplus/Resources/` and `./openstudiocore/resources/`)
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Debian, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run AutoDesk tests with new installer, Noah
- [x] Run hpxml tests with new installer, Scott
- [x] Run UrbanOpt example project with new installer, Tanushree
- [x] Create Carrier 32 bit Nuget package, Kyle
- [x] Test server changes with build zips, Anya
- [x] Create Release Notes (if needed), Tim
- [x] Release server (merge to master), Anya
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] Update the PAT SHA in OpenStudio, Tim
- [x] Github tag and release, Tim
- [x] Github tag and release OpenStudio-server, Tim
- [x] Upload packages to s3, Tim
- [x] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [x] Create and name AMIs, Anya
- [x] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

External distribution list for release candidate testing, Honeybee, Carrier

**Comment by jmarrec** [comment]
I suggest adding this to the Checklist:

**If New E+ release**:
* [ ] Bump E+ package in CMakeLists.txt
* [ ] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [ ] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./openstudiocore/src/energyplus/Resources/` and `./openstudiocore/resources/`)

**Comment by jmarrec** [comment]
@tijcolem Should probably be closed once last item is resolved, and the new items added to https://github.com/NREL/OpenStudio/issues/3526 instead
