### ISSUE TITLE
Update to EnergyPlus 9.3.0

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3902]
Enhancement Request
--------------

v9.3.0-IOFreeze is released, so we should update to it.

## Detailed Description

**When a checklist with a link to another issue was opened, means it will be treated over there**

### Major changes

https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/InputRulesFiles/Rules9-2-0-to-9-3-0.md

* [x] Fuel names replacements (**DONE** in #3904)
```
replace_dict = {
  'PropaneGas': 'Propane', 'FuelOil#': 'FuelOilNo'
}
```
* [ ] #3910 SizingPeriod:DesignDay gains a few field, but OS IDD has become quite out of line with E+
* [ ] #3908 ShadowCalculation changes a lot
* `HeatPump:WaterToWater:EIR:Cooling` (and Heating) become `HeatPump:PlantLoop:EIR:Cooling`
   * **Edit**: We actually do not use them
* [ ] #3905 - From IDD Diffing, it seems that `ZoneHVAC:TerminalUnit:VariableRefrigerantFlow` gained the ability to be connected to AirLoopHVAC

### New Additions

* [ ] #3907 - New `Coil:Cooling:DX` and `Coil:Cooling:DX:CurveFit:Performance`, `Coil:Cooling:DX:CurveFit:OperatingMode`,
* [ ] #3839 - Entire group `\group Python Plugin System`

### Minor stuff

* [x] #3903 - Add new fields to PerformancePrecisionTradeoffs (**DONE** in #3904)
* [x] Fan nodes are now `\required-field`, which I don't think has any impact for us.
* [ ] #3906 - E+ 9.3.0: Support new field 'Minimum Air Flow Turndown Schedule Name' for AirTerminals
* `AirTerminal:SingleDuct:Uncontrolled`, which was obsolete, is removed. This will not affect us as we transitioned to the new `AirTerminal:SingleDuct:ConstantVolume:NoReheat` already)
    * ATU:SingleDuct:CV:NoReheat is missing two fields at end: `Design Specification Outdoor Air Object Name` (replace with `Control For Outdoor Air` instead) and `Per Person Ventilation Rate Mode`

**Comment by wta12** [comment]
@kbenne @jmarrec @tijcolem : seems the last one: **A_TU:SingleDuct:CV:NoReheat is missing two fields at end: Design Specification Outdoor Air Object Name (replace with Control For Outdoor Air instead) and Per Person Ventilation Rate Mode** are not accessible in OS 3.0. Is there any plan for update OpenStudio with new _EP 9.3 BugFix_ ? Right now, there no way to modify those fields even with workspace EP.
