### ISSUE TITLE
OpenStudio 3.0.0 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#3924]
- [x] Release standards gem (0.2.11-rc2), Matt (waiting for official 0.2.11)
- [x] Release 2.0.0 workflow gem (2.0.0), Nick
- [x] Release extension gem (using pre-release Ref: Bump Deps)
- [x] Release measure tester gem (0.2.1), Nick
- [x] Double check gem files for correct versions of standards and workflow gems (use released versions only), Tim (Update workflow-gem to 2.0.0)
- [x] Build openstudio-gems tar.gz for develop and develop3 and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Debian, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run AutoDesk tests with new installer, Noah
- [x] Run hpxml tests with new installer, Scott
- [x] Run UrbanOpt example project with new installer, Tanushree
- [ ] Create Carrier 32 bit Nuget package, Kyle
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x] Release server (merge to master), Anya, Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim 
- [x] Github tag and release, Tim
- [x] Upload packages to s3, Tim
- [x] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [x] Create and name AMIs, Anya
- [x] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

**If New E+ release**:
* [x] Bump E+ package in CMakeLists.txt
* [x] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [x] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./src/energyplus/Resources/` and `./resources/`, cf `/path/to/build/resources/IdfFilesToTransition.lst`)

**Iteration 3.0.0-rc1 (03/24)**
Reported Issues
- Measure manager issue on osx darwin platform running rubocop 0.8.1 (fixed in rc2)
- Ruby bindings requiring .so segfault windows using mingw (investigating)
- Json warning issues (fixed rc2)
 - native extension gems not initing correctly on startup (fix coming for rc2) 

**Iteration 3.0.0-rc2 (04/06)**
Reported Issues
#3947 Fixed Calibration measure failure when reading time series (reported by Brian Ball) (fixed rc3)
#3942 Fixed Windows Ruby binding segfault (reported by Eric Bonnema)(fixed rc3)

**Iteration 3.0.0-rc3 (04/15)**
Reported Issues
CLI slowdown with rc2, this takes 0.1 seconds. With rc3, it takes 0.9 second using `require 'rexml/document'` (reported by Scott )
Check components for ruby API bindings.

**Comment by tijcolem** [comment]
Closing. We have another ticket for last item remaining - #3974
