### ISSUE TITLE
OpenStudio 3.1.0 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4051]
**Tentative Schedule**
|  |   |   |   |  |  |
|---|---|---|---|---|---|
| OS SDK v3.1.0  Code Freeze  | | | 2020-09-04  |  | 
| OS SDK v3.1.0 Release Candidate Start  | | | | 2020-09-25   |   
| OS SDK v3.1.0 Deliverable Final | | | | | 2020-10-16  |   
| EnergyPlus Code Freeze  | 2020-08-14  |  |||
| OS Standards Code Freeze  | |  2020-08-28  |   
| OS Extension Gems Code Freeze  | |  2020-08-28  |   
| OpenStudio Server Code Freeze  | |  2020-08-28  |  
| OS PAT Code Freeze    | |   2020-08-28  |  

**RC-4 released 10/15/20** (checklist below is for rc-4)

- [x] Release standards gem (0.2.12-rc7), Matt
- [x] Release 2.1.0 workflow gem (2.1.0), Nick
- [x] Release extension gem (0.3.1)
- [x] Release measure tester gem (0.2.3), Nick
- [x] Double check gem files for correct versions of standards and workflow gems (use released versions only), Tim 
- [x] Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Debian, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Kyle (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim 
- [x] Github tag and release, Tim
- [x] Upload packages to s3, Tim
- [x] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [x] Create and name AMIs, Anya
- [x] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

*New 9.4 E+ release**:
* [x] Bump E+ package in CMakeLists.txt
* [x] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [x ] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./src/energyplus/Resources/` and `./resources/`, cf `/path/to/build/resources/IdfFilesToTransition.lst`)
