### ISSUE TITLE
OpenStudio SDK 3.2.0 Release Checklist 

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4213]
**Tentative Schedule**
|  |   |   |   |  |  | |
|---|---|---|---|---|---|---|
| OS SDK v3.2.0  Code Freeze  | | |2021-03-31  |  | | |
| OS SDK v3.2.0 RC Start  | | | | 2021-04-15    |   | |
| OS SDK v3.2.0 Deliverable Final | | | | |  |   2021-05-14  |
| EnergyPlus IO Freeze  | 2021-02-19  |  | | | | |
| EnergyPlus Release |  |  |2021-03-31 || | |
| OS Standards RC Start  |  |2021-03-15   | | | |  |
| OS Standards Release   | | | 2021-03-31 |    | | |   |
| OS Extension Gems RC Start  | |2021-03-15   | | | |   |
| OpenStudio Server Code Freeze  | | 2021-03-15 |  | | | |
| OS PAT Code RC Start    | |  |  | | 2021-04-22 | |
| OS Server RC Start  | |  |  | |2021-04-22 | |

OS SDK 3.2.0-rc1 Checklist

- [x] Release standards gem (0.2.13), Matt
- [X] Release 2.2.x workflow gem (2.2.0), Nick
- [X] Release extension gem (0.4.2)
- [X] Release measure tester gem (0.3.0), Nick
- [X] Double check gem files for correct versions of standards and workflow gems, Tim 
- [X]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [X] Update resources and library files (if needed), Julien
- [X] Run Regression Tests, Julien
- [X] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [X] Test and Release OpenStudio Measures, David, Eric
- [X] Run BEST tests with new installer, David
- [X] Run Standards Tests with new installer, Matt
- [ ] Run hpxml tests with new installer, Scott
- [ ] Run UrbanOpt example project with new installer, Tim
- [X] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Kyle (Now with cmake build)
- [X] Test server changes with build zips, Tim
- [ ] Create Release Notes. API changes (if needed), Tim
- [ ] Release server (merge to master) Tim
- [X] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [X] Update the server SHA in PAT, Tim
- [X] PAT installer, Tim 
- [ ] Github tag and release, Tim
- [ ] Upload packages to s3, Tim
- [ ] Update Openstudio.net, Tim
- [ ] Update developer docs, Tim
- [ ] Create and name AMIs, Tim # Deprecated for 3.2.0
- [ ] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

*New 9.5 E+ release**:
* [X] Bump E+ package in CMakeLists.txt
* [x] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [X] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./src/energyplus/Resources/` and `./resources/`, cf `/path/to/build/resources/IdfFilesToTransition.lst`)
     * Note: this was done with 9.5.0-IOFreeze, but to be safe it should be done again with 9.5.0 official 

OS SDK 3.2.0 Checklist

- [x] Release standards gem (0.2.13), Matt
- [X] Release 2.2.x workflow gem (2.2.0), Nick
- [X] Release extension gem (0.4.2)
- [X] Release measure tester gem (0.3.0), Nick
- [X] Double check gem files for correct versions of standards and workflow gems, Tim 
- [X]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [X] Update resources and library files (if needed), Julien
- [X] Run Regression Tests, Julien
- [X] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [X] Test and Release OpenStudio Measures, David, Eric
- [X] Run BEST tests with new installer, David
- [X] Run Standards Tests with new installer, Matt
- [X] Run hpxml tests with new installer, Scott
- [X] Run UrbanOpt example project with new installer, Tim
- [X] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Kyle (Now with cmake build)
- [X] Test server changes with build zips, Tim
- [X] Create Release Notes. API changes (if needed), Tim
- [X] Release server (merge to master) Tim
- [X] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [X] Update the server SHA in PAT, Tim
- [X] PAT installer, Tim 
- [X] Github tag and release, Tim
- [X] Upload packages to s3, Tim
- [X] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [X] Create and name AMIs, Tim # Deprecated for 3.2.0
- [X] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

*New 9.5 E+ release**:
* [X] Bump E+ package in CMakeLists.txt
* [x] Bump `ENERGYPLUS_VERSION` in `ForwardTranslator.hpp`
* [X] Use the E+ transition utility (from official E+ package) to update the IDFs we store in our repo to the latest version (`./src/energyplus/Resources/` and `./resources/`, cf `/path/to/build/resources/IdfFilesToTransition.lst`)
     * Note: this was done with 9.5.0-IOFreeze, but to be safe it should be done again with 9.5.0 official
