### ISSUE TITLE
Release Checklist v3.2.1

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4321]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| OpenStudio SDK v3.2.1   |2021-05-28  | 2021-06-04  | 2021-06-30| 
| OpenStudio Server v3.2.1   |2021-05-28   | 2021-06-11 | 2021-06-30|
| OpenStudio PAT v3.2.1    |2021-05-28  | 2021-06-11 | 2021-06-30|

OS SDK 3.2.1-rc1 Checklist

- [x] Release standards gem (0.2.14), Matt
- [X] Release 2.2.0 workflow gem (2.2.1), Nick
- [X] Release extension gem (0.4.3)
- [X] Release measure tester gem (0.3.1), Nick
- [X] Double check gem files for correct versions of standards and workflow gems, Tim 
- [X]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Kyle (Now with cmake build)
- [x] Have Carrier test 64/32 bit Nuget package
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim 
- [x] Github tag and release, Tim
- [x] Upload packages to s3, Tim
- [x] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [x] Create and name AMIs, Tim # Deprecated for 3.2.1
- [x] Update OpenStudio Version Compatibility Matrix on Wiki, Tim
