### ISSUE TITLE
OpenStudio SDK 3.3.0 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4394]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| EnergyPlus    |2021-08-18  | 2021-09-15 | 2021-09-30 |
| OpenStudio SDK v3.3.0   |2021-09-30 | 2021-10-15 | 2021-11-05 | 
| OpenStudio Server v3.3.0   |2021-09-30   | 2021-10-15  | 2021-11-05|
| OpenStudio PAT v3.3.0    |2021-09-30 | 2021-10-15  | 2021-11-05|
| OpenStudio Standards Gem    |2021-09-01  | 2021-09-15 | 2021-09-30 |
| OpenStudio Extension Gem    |2021-09-01  | 2021-09-15 | 2021-09-30 |
| UrbanOpt-CLI-Gem    |2021-09-01  | 2021-09-15 | 2021-09-30 |

OS SDK v3.3.0 Checklist

- [x] Release standards gem (0.2.15), Matt
- [x] Release 2.3.1 workflow gem (2.3.1), Nick
- [x] Release extension gem (0.5.1)
- [x] Release measure tester gem (0.3.1), Nick
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Kyle (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim 
- [x] Github tag and release, Tim
- [x] Upload packages to s3, Tim
- [x] Update Openstudio.net, Tim
- [x] Update developer docs, Tim
- [ ] Create and name AMIs, Tim # Deprecated for 3.3.0
- [x] Update OpenStudio Version Compatibility Matrix on Wiki, Tim

**Comment by eringold** [comment]
Update SDK documentation to show 3.3.0 as latest iteration: 
https://s3.amazonaws.com/openstudio-sdk-documentation/index.html

**Comment by tijcolem** [comment]
@eringold v3.3.0 is now the latest at https://s3.amazonaws.com/openstudio-sdk-documentation/index.html

**Comment by tijcolem** [comment]
closing issue as v3.3.0 is released.
