### ISSUE TITLE
OpenStudio 3.4 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4545]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| EnergyPlus  22.1.0  |2022-02-24  | 2022-03-15 | 2022-03-31 |
| OpenStudio SDK v3.4.0   |2022-03-15 | 2022-04-07 | 2022-05-12 | 
| OpenStudio Server v3.4.0   |2022-03-30   | 2022-04-15  | 2022-05-12|
| OpenStudio PAT v3.4.0    |2022-03-30 | 2022-04-15  | 2022-05-12|
| OpenStudio Standards Gem    |2022-03-07  | 2022-03-15 | 2022-03-30 |
| OpenStudio Extension Gem    |2022-03-07  | 2022-03-15 | 2022-03-30 |
| UrbanOpt-CLI-Gem    |  |  |  |

OS SDK v3.4.0 Checklist

- [x] Release standards gem (0.2.16), Matt
- [x] Release 2.3.1 workflow gem (2.3.1), Nick
- [x] Release extension gem (0.5.1)
- [x] Release measure tester gem (0.3.1), Nick
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
    - https://github.com/NREL/OpenStudio/pull/4562
- [-] Run Regression Tests, Julien
    - [x] Done with 0eb8ab883b (based on 22.1.0-RC1)
    - [x] Do with openstudio SDK
- [x] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run Measure tests with new installer, David
    - [x] openstudio-model-articulation-gem
    - [x] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Tim (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x]  Update SDK docs (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim
