### ISSUE TITLE
OpenStudio 3.5 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4633]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  22.2.0  |2022-08-19  | 2022-09-15 | 2022-09-30 |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.5.0   |2022-09-30 | 2022-10-15 | 2022-11-09 | 
| OpenStudio Server v3.5.0   |2022-09-30   | 2022-10-15  | 2022-11-09|
| OpenStudio PAT v3.5.0    |2022-09-30| 2022-10-15  | 2022-11-09|
| OpenStudio Standards Gem    |2022-09-15  | 2022-09-30 | 2022-10-15 |
| OpenStudio Extension Gem    |2022-09-15 | 2022-09-30 | 2022-10-15 |
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2022-10-15 | 2022-11-01 | 2022-11-15 |
| openstudio-aedg-gem  |2022-10-15 | 2022-11-01 | 2022-11-15 |
| openstudio-load-flexibility-measures-gem  |2022-10-15 | 2022-11-01 | 2022-11-15 |
| openstudio-ee-gem  |2022-10-15 | 2022-11-01 | 2022-11-15 |
| openstudio-common-measures-gem |2022-10-15 | 2022-11-01 | 2022-11-15 |
| openstudio-calibration-gem |2022-10-15 | 2022-11-01 | 2022-11-15 |

OS SDK v3.5.0 Checklist

- [x] Release standards gem (0.3.0), Matt
- [x] Release workflow gem (2.3.1), Nick
- [x] Release extension gem (0.6.0), Nick
- [x] Release measure tester gem (0.3.2), Nick
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
    - [x] Do with openstudio SDK
- [x] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run Measure tests with new installer, David
    - [x] openstudio-model-articulation-gem
    - [x] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Tim (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x]  Update SDK docs (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim
