### ISSUE TITLE
OpenStudio 3.5.1 Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4765]
OS SDK v3.5.1 Checklist

- [x] Release standards gem (0.3.0), Matt
- [x] Release workflow gem (2.3.1), Nick
- [x] Release extension gem (0.6.0), Nick
- [x] Release measure tester gem (0.3.2), Nick
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Tim
    - [x] Do with openstudio SDK
- [x] Create Ubuntu 1804, Ubuntu 2004, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run Measure tests with new installer, David
    - [x] openstudio-model-articulation-gem
    - [x] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Tim (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x]  Update SDK docs (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim
