### ISSUE TITLE
Release Checklist v3.6.0

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4794]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  23.1.0  |2023-02-20  | 2023-03-15 | 2023-03-31  |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.6.0   |2023-03-15 | 2023-04-07 | 2023-05-12 | 
| OpenStudio Server v3.6.0   |2023-03-30   | 2023-04-15  | 2023-05-12|
| OpenStudio PAT v3.6.0    |2023-03-30 | 2023-04-15  | 2023-05-12|
| OpenStudio Standards Gem    |2023-03-07  | 2023-03-15 | 2023-03-30 |
| OpenStudio Extension Gem    |2023-03-07  | 2023-03-15 | 2023-03-30 |
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2023-04-12 | 2023-05-05 |  2023-05-19 |
| openstudio-aedg-gem  |2023-04-12|  2023-05-05 | 2023-05-19  |
| openstudio-load-flexibility-measures-gem  |2023-04-12| 2023-05-05  | 2023-05-19 |
| openstudio-ee-gem  |2023-04-12 |  2023-05-05  | 2023-05-19 |
| openstudio-common-measures-gem |2023-04-12 |  2023-05-05  | 2023-05-19 |
| openstudio-calibration-gem |2023-04-12 |  2023-05-05  | 2023-05-19 |

OS SDK v3.6.0-rc3 Checklist

- [x] Release standards gem (0.4.0), Matt
- [x] Release workflow gem (2.3.1), Nick
- [x] Release extension gem (0.6.0), Nick
- [x] Release measure tester gem (0.3.2), Nick
- [x] Update to latest TBD gem (3.2.2), Tim
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
     -  Re-export resources/utilities/SqlFile/1ZoneEvapCooler-V23-1-0.idf with official E+
- [x] Run Regression Tests, Julien
    - [x] Do with openstudio SDK
- [x] Create Ubuntu 2004, Ubuntu 2204, Centos7, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [ ] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [ ] (new) Run resstock tests with new installer, Joe
- [x] Run Measure tests with new installer, David
    - [x] openstudio-model-articulation-gem
    - [x] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Run UrbanOpt (0.9.2) example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Tim (Now with cmake build)
- [x] Test server changes with build zips, Tim
- [x]  Run OpenStudio-server-helm with latest server containers, Tim
- [ ] Create Release Notes. API changes (if needed), Tim
- [ ]  Update SDK docs (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim 

OS SDK v3.6.0 Checklist

- [x] Release standards gem (0.X.X), Matt
- [x] Release workflow gem (2.X.X), Nick
- [x] Release extension gem (0.6.0), Nick
- [x] Release measure tester gem (0.X.X), Nick
- [x] Update to latest TBD gem (X.X.X), Tim
- [x] Double check gem files for correct versions of standards and workflow gems, Tim 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Tim
- [x] Update resources and library files (if needed), Julien
     -  Re-export resources/utilities/SqlFile/1ZoneEvapCooler-V23-1-0.idf with official E+
- [x] Run Regression Tests, Julien
    - [x] Do with openstudio SDK
- [x] Create Ubuntu 2004, Ubuntu 2204, Centos7, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run Measure tests with new installer, David
    - [x] openstudio-model-articulation-gem
    - [x] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Run UrbanOpt example project with new installer, Tim
- [x] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Tim (Now with cmake build)
    - #4887  
- [x] Test server changes with build zips, Tim
- [x] Create Release Notes. API changes (if needed), Tim
- [x]  Update SDK docs (if needed), Tim
- [x] Release server (merge to master) Tim
- [x] Build Server packages, post on S3, Tim - Windows, Tim - Mac
- [x] Update the server SHA in PAT, Tim
- [x] PAT installer, Tim

**Comment by mdahlhausen** [comment]
Suggest adding an item to the release checklist to update the [TBD gem](https://github.com/rd2/tbd).

**Comment by jmarrec** [comment]
C# nuget is failing due to https://github.com/NREL/OpenStudio/issues/4887
