### ISSUE TITLE
Release Checklist v3.7.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4967]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  23.2.0  |2023-09-15   | 2023-09-22  | 2023-09-29  |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.7.0   |2023-09-29 | 2023-10-16 | 2023-11-10 | 
| OpenStudio Server v3.7.0   |2023-10-06   | 2023-10-23  | 2023-11-10|
| OpenStudio PAT v3.7.0    |2023-10-06 | 2023-10-30 | 2023-11-10|
| OpenStudio Standards Gem    |2023-09-29  | 2023-10-06 | 2023-10-13 |
| OpenStudio Extension Gem    |2023-09-29  | 2023-10-06| 2023-10-13 |
| openstudio-measure-tester-gem  |2023-09-29  | 2023-10-06| 2023-10-13 |
| openstudio-workflow_gem  |2023-09-29  | 2023-10-06| 2023-10-13 |
| openstudio-analysis_gem  |2023-09-29  | 2023-10-23| 2023-11-10 |
| openstudio-aws_gem  |2023-09-29  | 2023-10-23| 2023-11-10 |
| some urbanopt gems?  |2023-09-29  | 2023-10-23| 2023-11-10 |
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2023-10-13 | 2023-10-27 |  2023-11-17 |
| openstudio-aedg-gem  |2023-10-13 | 2023-10-27 |  2023-11-17 |
| openstudio-load-flexibility-measures-gem  |2023-10-13 | 2023-10-27 |  2023-11-17 |
| openstudio-ee-gem  |2023-10-13 | 2023-10-27 |  2023-11-17 |
| openstudio-common-measures-gem |2023-10-13 | 2023-10-27 |  2023-11-17 |
| openstudio-calibration-gem |2023-10-13 | 2023-10-27 |  2023-11-17 |
| **Other Measure Repositories**    | |  |  |
| BESTEST-GSR |2023-11-17 | 2023-11-24 |  2023-12-01 |

OS SDK v3.7.0 Checklist

- [ ] Release standards gem (0.5.0), Matt
- [ ] Release workflow gem (2.X.X), Nicholas
- [x] Release extension gem (0.7.0), Nicholas
- [ ] Release measure tester gem (0.X.X), Nick
- [ ] Release analysis gem (0.X.X), Brian
- [ ] Release aws gem (0.X.X), Brian
- [ ] Release required URBANopt gems used for OSAF (0.X.X), Katherine
- [x] Update to latest TBD gem (X.X.X), Wenyi
- [ ] Double check gem files for correct versions of standards and workflow gems, Wenyi 
- [ ]  Build openstudio-gems tar.gz for develop and upload to s3., Wenyi
- [x] Update to EnergyPlus 23.2
    - #4934 
    - #4941 
- [x] Update resources and library files (if needed), Julien
     -  Re-export resources/utilities/SqlFile/1ZoneEvapCooler-V23-1-0.idf with official E+
- [x] Run Regression Tests, Julien
    - [ ] Do with openstudio SDK
    - #4977 
- [ ] 3.7.0 critical tagged issues fixed
    - #4941 
    - #4946 
    - #4945 
    - #4544 
    - #4907
    - #4929 
    - #4895   
- [ ] Look at open OpenStudio PRs
- [ ] Create Ubuntu 2004, Ubuntu 2204, Centos7, Darwin, and Windows untested build zips and upload to S3, Wenyi
- [ ] Run BEST tests with new installer, Dareum
- [ ] Run Standards Tests with new installer, Matt
- [ ] Run hpxml tests with new installer, Scott
- [x] Run resstock tests with new installer, Joe
- [ ] Run Measure tests with new installer, Joe, David
    - [ ] openstudio-model-articulation-gem
    - [ ] openstudio-aedg-gem
    - [ ] openstudio-load-flexibility-measures
    - [ ] openstudio-common-measures-gem
    - [ ] openstudio-calibration-gem
    - [ ] openstudio-ee-gem
- [ ] Release OpenStudio Measures, Nicholas
- [ ] Run UrbanOpt example project with new installer, Wenyi
- [ ] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Wenyi (Now with cmake build)
    - https://github.com/NREL/OpenStudio/pull/5049#issuecomment-1819035028
- [ ] Test server changes with build zips, Wenyi
- [ ] Create Release Notes. API changes (if needed), Wenyi
   - Gather key new features from team for release notes, David
- [ ]  Update SDK docs (if needed), Wenyi
- [ ] Release server (merge to master) Wenyi
- [ ] Build Server packages, post on S3, Wenyi - Windows, Wenyi - Mac
- [ ] Update the server SHA in PAT, Wenyi
- [ ] PAT installer, Wenyi
