### ISSUE TITLE
Release Checklist v3.8.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5102]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  24.1.0  |2024-02-20  | 2024-03-15| 2024-04-01 |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.8.0   |2024-03-27 |2024-04-07| 2024-05-17| 
| OpenStudio Server v3.8.0   |2024-03-30   | 2024-04-15| 2024-05-17|
| OpenStudio PAT v3.8.0    |2024-03-30 | 2024-04-15</li>  | 2024-05-17|
| openstudio-standards Gem v0.6.0    |2024-04-05  | 2024-04-12| 2024-04-19|
| OpenStudio Extension Gem v0.8.0    |2024-03-15  | 2024-03-27| 2024-04-05|
| openstudio-measure-tester-gem v0.4.0  |2024-03-15  | 2024-03-27| 2024-04-05|
| openstudio-workflow_gem v2.4.0 |2024-03-15  | 2024-03-27| 2024-04-05|
| bcl_gem v0.8.0 |2024-03-15  | 2024-03-27| 2024-04-05|
| openstudio-analysis_gem  |2024-03-15  | 2024-03-27| 2024-04-05|
| openstudio-aws_gem  |2024-03-15  | 2024-03-27| 2024-04-05|
| some urbanopt gems? |2024-03-15  | 2024-03-27| 2024-04-05|
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2024-04-12 | 2024-05-05|2024-05-20|
| openstudio-aedg-gem  |2024-04-12 | 2024-05-05|2024-05-20|
| openstudio-load-flexibility-measures-gem  |2024-04-12 | 2024-05-05|2024-05-20|
| openstudio-ee-gem  |2024-04-12 | 2024-05-05|2024-05-20|
| openstudio-common-measures-gem |2024-04-12 | 2024-05-05|2024-05-20|
| openstudio-calibration-gem |2024-04-12 | 2024-05-05|2024-05-20|
| **Other Measure Repositories**    | |  |  |
| BESTEST-GSR |2024-04-12 | 2024-05-05|2024-05-27|

OS SDK v3.8.0 Checklist

- [x] Release standards gem (0.6.0), Matt
- [x] Release workflow gem (2.4.0), Nicholas
- [x] Release extension gem (0.7.0), Nicholas
- [x] Release measure tester gem (0.4.0), Nick
- [x] bcl gem (0.8.0), Nick
- [ ] Release analysis gem (0.X.X), Brian
- [ ] Release aws gem (0.X.X), Brian
- [ ] Release required URBANopt gems used for OSAF (0.X.X), Katherine
- [ ] Update to latest TBD gem (X.X.X), Wenyi
- [ ] Double check gem files for correct versions of standards and workflow gems, Wenyi 
- [ ]  Build openstudio-gems tar.gz for develop and upload to s3., Wenyi
- [x] Update to EnergyPlus 24.1
- [ ] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
    - [x] Do with openstudio SDK
- [ ] 3.8.0 critical tagged issues fixed
    - [x] #5145 (?)
    - [x] #5143 
    - [x] #5191 
    - [x] #5194 
    - [x] #5196 
    - [ ] RuboCop issue new to rc3 
    - [ ] OSAF Mac and Linux integration tests are failing
    - [ ] See this on all create_typical tests `TypeError: Expected argument 1 of type std::vector< openstudio::model::Material >::value_type const &, but got OpenStudio::Model::OptionalMaterial #<OpenStudio::Model::OptionalM...` (Matt and David)
    - [ ] openstudio-standards-0.6.0/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:7399]: NoMethodError: undefined method `include?' for nil:NilClass
    - [ ] 4 create_bar tests that shold be failing are passing, need to address what happens with bad args.
    - [ ] Problem with model_apply_parametric_schedules in inspect schedule in calibration repo (David and Matt)
    - [x] NoMethodError: undefined method `SqlFilemake_qaqc_results_vector' for OpenstudioStandards:Module (this is 
    - [ ] impacting Xcel QAQC measure, see if Matt knows if this changed)
    - [ ] inspectAndEditParametricSchedules: only test errors getting optional not initialized on model_apply_parametric_schedules (follow up with Matt on this, did additional property para schedule inputs change?)
    - [x] Resolve issues with measure gems and measure repo CI, Wenyi
    - [ ] Check if any gems need to get updated before final 3.8.0 (Wenyi)
- [ ] Look at open OpenStudio PRs
- [ ] Create Ubuntu 2004, Ubuntu 2204, Centos7, Darwin, and Windows untested build zips and upload to S3, Wenyi
- [ ] Run BEST tests with new installer, Dareum
- [ ] Sanity test install packages on clean VMs with default OS installations, Wenyi
- [ ] Run Standards Tests with new installer, Matt
- [ ] Run hpxml tests with new installer, Scott
- [ ] Run resstock tests with new installer, Joe
- [ ] Run Measure tests with new installer, Joe, David
    - [ ] openstudio-model-articulation-gem
    - [ ] openstudio-aedg-gem
    - [ ] openstudio-load-flexibility-measures
    - [ ] openstudio-common-measures-gem
    - [ ] openstudio-calibration-gem
    - [ ] openstudio-ee-gem
- [ ] Release OpenStudio Measures, Nicholas
- [ ] Run UrbanOpt example project with new installer, Wenyi
- [ ] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Wenyi (Now with cmake build)
- [ ] Test server changes with build zips, Wenyi
- [ ] Create Release Notes. API changes (if needed), David
   - [ ] Gather key new features from team for release notes,
   - [ ] populate change log sections (use script to support this)
   - [ ] Update name from OpenStudio_Release_Notes_3_8_0_TBD to YYYYMMDD
   - [ ] Make PDF copy of md once finalized
- [ ]  Update SDK docs (if needed), Wenyi
- [ ] Release server (merge to master) Wenyi
- [ ] Build Server packages, post on S3, Wenyi - Windows, Wenyi - Mac
- [ ] Update the server SHA in PAT, Wenyi
- [ ] PAT installer, Wenyi
