### ISSUE TITLE
Release Checklist v3.9.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5256]
**Tentative Schedule**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  24.2.0  |2024-09-15   | 2024-09-22  | 2024-09-30  |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.9.0   |2024-09-30 | 2024-10-18 | 2024-11-15 | 
| OpenStudio Server v3.9.0   |2024-10-11   | 2024-10-25  | 2024-11-15|
| OpenStudio PAT v3.9.0    |2024-10-11 | 2024-10-30 | 2024-11-15|
| OpenStudio Standards Gem    |2024-10-18 | 2024-10-25 | 2024-11-1 |
| OpenStudio Extension Gem    |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-measure-tester-gem  |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-workflow_gem  |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-analysis_gem  |2024-09-30  | 2024-10-25| 2024-11-10 |
| openstudio-aws_gem  |2024-09-30  | 2024-10-25| 2024-11-10 |
| some urbanopt gems?  |2024-09-30  | 2024-10-25| 2024-11-10 |
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-aedg-gem   |2024-10-18 | 2024-11-01 |  2024-11-25 |
| openstudio-load-flexibility-measures-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-ee-gem   |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-common-measures-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-calibration-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| **Other Measure Repositories**    | |  |  |
| BESTEST-GSR |2024-11-15 | 2024-11-24 |  2024-12-02 |

OS SDK v3.9.0 Checklist

- [x] Release standards gem (0.7.0.rc1), Matt 
- [x] Release standards gem (0.7.0), Matt
- [x] Release extension gem (0.8.2)?, Katherine
- (No Update Needed) [x] Release measure tester gem (0.4.0)?, Katherine
- (No Update Needed) [x] bcl gem (0.8.0)?, Katherine
- (No Update Needed) [x] Release analysis gem (1.4.0), Brian
- (No Update Needed) [x] Release aws gem (0.X.X), Brian
- [x] Release required URBANopt gems used for OSAF (0.X.X), Katherine
- [x] Add OSut (v0.6.0) TBD dependency, Wenyi (https://rubygems.org/gems/osut)
- [x] Update to latest TBD gem (3.4.3), Wenyi (https://rubygems.org/gems/tbd)
- [x] Double check gem files for correct versions of standards and workflow gems, Wenyi 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Wenyi
- [x] Update to EnergyPlus 24.2
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] 3.9.0 critical tagged issues fixed
    - [x] RuboCop issue new to rc3 
    - [x] OSAF Mac and Linux integration tests are failing
    - [x] See this on all create_typical tests `TypeError: Expected argument 1 of type std::vector< openstudio::model::Material >::value_type const &, but got OpenStudio::Model::OptionalMaterial #<OpenStudio::Model::OptionalM...` (Matt and David)
    - [x] openstudio-standards-0.6.0/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:7399]: NoMethodError: undefined method `include?' for nil:NilClass
    - [x] 4 create_bar tests that shold be failing are passing, need to address what happens with bad args.
    - [x] Problem with model_apply_parametric_schedules in inspect schedule in calibration repo (David and Matt)
    - [x] impacting Xcel QAQC measure, see if Matt knows if this changed)
    - [x] inspectAndEditParametricSchedules: only test errors getting optional not initialized on model_apply_parametric_schedules (follow up with Matt on this, did additional property para schedule inputs change?)
    - [x] Resolve issues with measure gems and measure repo CI, Wenyi
    - [x] Check if any gems need to get updated before final release (Wenyi)
- [x] Look at open OpenStudio PRs
- [x] Create Ubuntu 2004, Ubuntu 2204, Darwin, and Windows untested build zips and upload to S3 (in future support Centos9), Wenyi
- [x] Run BEST tests with new installer, David
- [x] Sanity test install packages on clean VMs with default OS installations, Wenyi
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run resstock tests with new installer, Joe
- [x] Close items needed for 3.9.0 on measure gems project, David (https://github.com/orgs/NREL/projects/25/views/1?layout=board)
- [ ] Run Measure tests with new installer, Joe, David
    - [x] openstudio-model-articulation-gem
    - [ ] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Release OpenStudio Measures, Katherine
- [ ] Run UrbanOpt example project with new installer, Wenyi
- [ ] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Wenyi (Now with cmake build)
- [x] Test server changes with build zips, Wenyi
- [x] Create Release Notes. API changes (if needed), David
   - [x] Gather key new features from team for release notes,
   - [x] populate change log sections (use script to support this)
   - [x] Update name from OpenStudio_Release_Notes_3_9_0_TBD to YYYYMMDD
   - [x] Make PDF copy of md once finalized
   - [ ] Update content from Release Notes to GitHub Release page, Wenyi
- [x]  Update SDK docs (if needed), Wenyi
- [x]  Update OpenStudio-SDK-Version-Compatibility-Matrix on wiki, Wenyi
- [ ] Release server (merge to master) Wenyi
- [ ] Build Server packages, post on S3, Wenyi - Windows, Wenyi - Mac
- [ ] Update the server SHA in PAT, Wenyi
- [ ] PAT installer, Wenyi

**Comment by jmarrec** [comment]
I built and uploaded the centos7 RPM, linux arm64 builds (TGZ and DEB for both Ubuntu 22.04 and 24.04).

**Comment by jmarrec** [comment]
Where are we on this checklist? We're 17 days past the latest release date in the table above, yet some items are still not checked and this issue is still open.

I see PAT at least never got released. https://github.com/NREL/OpenStudio-PAT/releases
