### ISSUE TITLE
Release Checklist v3.10.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5323]
**Tentative Schedule - David to replace dates from 3.9.0 here**
|   |  Code Freeze | Release Candidates  |  Release | 
|---|---|---|---|
| **EnergyPlus**    | |  |  |
| EnergyPlus  24.2.0  |2024-09-15   | 2024-09-22  | 2024-09-30  |
| **OpenStudio**    | |  |  |
| OpenStudio SDK v3.9.0   |2024-09-30 | 2024-10-18 | 2024-11-15 | 
| OpenStudio Server v3.9.0   |2024-10-11   | 2024-10-25  | 2024-11-15|
| OpenStudio PAT v3.9.0    |2024-10-11 | 2024-10-30 | 2024-11-15|
| OpenStudio Standards Gem    |2024-10-18 | 2024-10-25 | 2024-11-1 |
| OpenStudio Extension Gem    |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-measure-tester-gem  |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-workflow_gem  |2024-09-30  | 2024-10-04| 2024-10-15 |
| openstudio-analysis_gem  |2024-09-30  | 2024-10-25| 2024-11-10 |
| openstudio-aws_gem  |2024-09-30  | 2024-10-25| 2024-11-10 |
| some urbanopt gems?  |2024-09-30  | 2024-10-25| 2024-11-10 |
| **Measure Gems**    | |  |  |
| openstudio-model-articulation-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-aedg-gem   |2024-10-18 | 2024-11-01 |  2024-11-25 |
| openstudio-load-flexibility-measures-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-ee-gem   |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-common-measures-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| openstudio-calibration-gem  |2024-10-11 | 2024-10-25 |  2024-11-18 |
| **Other Measure Repositories**    | |  |  |
| BESTEST-GSR |2024-11-15 | 2024-11-24 |  2024-12-02 |

OS SDK v3.9.0 Checklist

- [x] Release standards gem (0.7.0.rc1), Matt 
- [x] Release standards gem (0.7.0), Matt
- [x] Release extension gem (0.8.2)?, Katherine
- (No Update Needed) [x] Release measure tester gem (0.4.0)?, Katherine
- (No Update Needed) [x] bcl gem (0.8.0)?, Katherine
- (No Update Needed) [x] Release analysis gem (1.4.0), Brian
- (No Update Needed) [x] Release aws gem (0.X.X), Brian
- [ ] Release required URBANopt gems used for OSAF (0.X.X), Katherine
- [x] Add OSut (v0.6.0) TBD dependency, Wenyi (https://rubygems.org/gems/osut)
- [x] Update to latest TBD gem (3.4.3), Wenyi (https://rubygems.org/gems/tbd)
- [x] Double check gem files for correct versions of standards and workflow gems, Wenyi 
- [x]  Build openstudio-gems tar.gz for develop and upload to s3., Wenyi
- [x] Update to EnergyPlus 24.2
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] 3.9.0 critical tagged issues fixed
    - [x] RuboCop issue new to rc3 
    - [x] OSAF Mac and Linux integration tests are failing
    - [x] See this on all create_typical tests `TypeError: Expected argument 1 of type std::vector< openstudio::model::Material >::value_type const &, but got OpenStudio::Model::OptionalMaterial #<OpenStudio::Model::OptionalM...` (Matt and David)
    - [x] openstudio-standards-0.6.0/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:7399]: NoMethodError: undefined method `include?' for nil:NilClass
    - [x] 4 create_bar tests that shold be failing are passing, need to address what happens with bad args.
    - [x] Problem with model_apply_parametric_schedules in inspect schedule in calibration repo (David and Matt)
    - [x] impacting Xcel QAQC measure, see if Matt knows if this changed)
    - [x] inspectAndEditParametricSchedules: only test errors getting optional not initialized on model_apply_parametric_schedules (follow up with Matt on this, did additional property para schedule inputs change?)
    - [x] Resolve issues with measure gems and measure repo CI, Wenyi
    - [x] Check if any gems need to get updated before final release (Wenyi)
- [x] Look at open OpenStudio PRs
- [x] Create Ubuntu 2004, Ubuntu 2204, Darwin, and Windows untested build zips and upload to S3 (in future support Centos9), Wenyi
- [x] Run BEST tests with new installer, David
- [x] Sanity test install packages on clean VMs with default OS installations, Wenyi
- [x] Run Standards Tests with new installer, Matt
- [x] Run hpxml tests with new installer, Scott
- [x] Run resstock tests with new installer, Joe
- [x] Close items needed for 3.9.0 on measure gems project, David (https://github.com/orgs/NREL/projects/25/views/1?layout=board)
- [ ] Run Measure tests with new installer, Joe, David
    - [x] openstudio-model-articulation-gem
    - [ ] openstudio-aedg-gem
    - [x] openstudio-load-flexibility-measures
    - [x] openstudio-common-measures-gem
    - [x] openstudio-calibration-gem
    - [x] openstudio-ee-gem
- [x] Release OpenStudio Measures, Katherine
- [ ] Run UrbanOpt example project with new installer, Wenyi
- [ ] Create Carrier 64/32 bit Nuget package and upload to nuget.org, Wenyi (Now with cmake build)
- [x] Test server changes with build zips, Wenyi
- [x] Create Release Notes. API changes (if needed), David
   - [x] Gather key new features from team for release notes,
   - [x] populate change log sections (use script to support this)
   - [x] Update name from OpenStudio_Release_Notes_3_9_0_TBD to YYYYMMDD
   - [x] Make PDF copy of md once finalized
   - [ ] Update content from Release Notes to GitHub Release page, Wenyi
- [x]  Update SDK docs (if needed), Wenyi
- [x]  Update OpenStudio-SDK-Version-Compatibility-Matrix on wiki, Wenyi
- [ ] Release server (merge to master) Wenyi
- [ ] Build Server packages, post on S3, Wenyi - Windows, Wenyi - Mac
- [ ] Update the server SHA in PAT, Wenyi
- [ ] PAT installer, Wenyi

**Comment by DavidGoldwasser** [comment]
3.10.0-rc4 measure testing on local Windows.

Load Flex
19 tests, 239 assertions, 0 failures, 0 errors, 0 skips

Calibration
22 tests, 278 assertions, 0 failures, 0 errors, 1 skips

EE
84 tests, 1036 assertions, 4 failures, 0 errors, 0 skips
1 is GLHEProExportLoadsforGroundHeatExchangerSizing_Test2 (David Investigate)
3 are NzeHvac_Test13 (follow up with Matt)

Common (on branch for PR#195 that fixes OS Results rendering)
196 tests, 1817 assertions, 0 failures, 0 errors, 10 skips

Model Articulation
343 tests, 1887 assertions, 3 failures, 71 errors, 21 skips
3 errors CreateBaselineBuildingTest
3 failures CreateDOEPrototypeBuildingTest and CreateDEERPrototypeBuildingTest
60 errors CreateTypicalBuildingFromModel_Test (Check with Matt)
1 errors CreateTypicalDEERBuildingFromModel_Test (Check with Matt)
7 errors CreateTypicalDOEBuildingFromModel_Test (Check with Matt)




60 errors for CreateTypicalBuildingFromModel_Test look like this (plus 1 DEER and 6 DOE)
:/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/exterior_lighting/create.rb:163

NoMethodError: undefined method `[]' for false:FalseClass
    :/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/exterior_lighting/create.rb:163:in `model_create_typical_exterior_lighting'
    :/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/create_typical/create_typical.rb:461:in `create_typical_building_from_model'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_building_from_model/measure.rb:478:in `run'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb:74:in `apply_measure_to_model'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb:530:in `test_wrf_hpwh'

1 of the create typical DOE measure errors are this refrigeration error

:/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/refrigeration/create_typical_refrigeration.rb:19

NoMethodError: undefined method `[]' for false:FalseClass
    :/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/refrigeration/create_typical_refrigeration.rb:19:in `create_typical_refrigeration'
    :/ruby/3.2.0/gems/openstudio-standards-0.8.0/lib/openstudio-standards/create_typical/create_typical.rb:566:in `create_typical_building_from_model'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/measure.rb:481:in `run'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/create_typical_doe_building_from_model_test.rb:77:in `apply_measure_to_model'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/create_typical_doe_building_from_model_test.rb:143:in `test_small_office_no_extra_loads_with_pvav'

**Comment by DavidGoldwasser** [comment]
OpenStudio Results was fine on same machine when I ran `openstudio my_test.rb` See log below. I'm going to clean out test output directory for this measure and re run `openstudio measure -r` again for that repo.

Finished in 765.374506s, 0.0118 runs/s, 0.1607 assertions/s.

`9 runs, 123 assertions, 0 failures, 0 errors, 0 skips
PS C:\Users\dgoldwas\Documents\GitHub\NREL> openstudio .\openstudio-common-measures-gem\lib\measures\openstudio_results\tests\OpenStudioResults_Test.rb^C`

**Comment by DavidGoldwasser** [comment]
OpenStudio-3.10.0-rc5+e2e9b52d54-Darwin-arm64 Measure Testing Mac local
model articulation
343 tests, 1887 assertions, 4 failures, 71 errors, 21 skips

CreateBarFromDOEBuildingTypeRatios_Test (1 fail) This was only on Mac and not on Windows
test_multi_rot_a

CreateBaselineBuildingTest (3 errors)
2007_sec_schoolAssertions, 2010_sec_schoolAssertions, 2013_sec_schoolAssertions
:/ruby/3.2.0/gems/openstudio-standards-0.8.1/lib/openstudio-standards/standards/Standards.ThermalZone.rb:302
ArgumentError: comparison of Float with nil failed

CreateDEERPrototypeBuildingTest (1 fail)
test_asmAssertions

CreateDOEPrototypeBuildingTest2 (2 fail)
test_primary_schoolAssertions
test_secondary_schoolAssertions
FAILURES: Error - PrimarySchool-90.1-2004-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-90.1-2007-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-90.1-2010-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-90.1-2016-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-DOE Ref 1980-2004-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-DOE Ref Pre-1980-ASHRAE 169-2013-3A - Model was not created successfully.

CreateTypicalBuildingFromModel_Test (60 errors)
:/ruby/3.2.0/gems/openstudio-standards-0.8.1/lib/openstudio-standards/exterior_lighting/create.rb:163
NoMethodError: undefined method `[]' for false:FalseClass

for create_typical, when I run it by calling `ruby tests\create_typical_building_from_model_test.rb` It comes back clean. This seems like issue is related to the finding file issue? May run OSW and see if that works. Run with CLI and OSApp?
Finished in 644.791685s, 0.0946 runs/s, 0.4389 assertions/s.
61 runs, 283 assertions, 0 failures, 0 errors, 1 skips

CreateTypicalDEERBuildingFromModel_Test1 (1 error - same as above)

CreateTypicalDOEBuildingFromModel_Test (7 errors - same as above)

**Comment by DavidGoldwasser** [comment]
OpenStudio-3.10.0-rc5+e2e9b52d54-Darwin-arm64 Measure Testing Mac local
common-measures
196 tests, 1818 assertions, 0 failures, 0 errors, 10 skips

calibration-measures
22 tests, 278 assertions, 0 failures, 0 errors, 1 skips

load-flexibility
19 tests, 239 assertions, 0 failures, 0 errors, 0 skips

**Comment by DavidGoldwasser** [comment]
OpenStudio-3.10.0-rc5+e2e9b52d54-Darwin-arm64 Measure Testing Mac local
ee-measures
84 tests, 1039 assertions, 3 failures, 0 errors, 0 skips

NzeHvac_Test (3 failures)
test_model_with_sizing_issuesAssertions
test_office_pvav_reheatAssertions
test_office_vav_reheatAssertions
